# Generated by Django 4.1 on 2024-04-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='List_of_items',
        ),
    ]
